language: ruby
cache: bundler
rvm: 2.2.0
sudo: false
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle update contracto-rspec
  - bundle exec rake db:create db:schema:load --trace